# Generated by Django 5.2 on 2025-07-16 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audir', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HandImage',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='fname',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pname',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='result',
            name='project',
        ),
        migrations.AddField(
            model_name='result',
            name='length_index',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='length_ring',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='result_image',
            field=models.ImageField(blank=True, null=True, upload_to='result/'),
        ),
    ]
