# Generated by Django 5.2 on 2025-07-16 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audir', '0002_delete_handimage_rename_fname_image_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audir.project'),
        ),
    ]
