# Generated by Django 5.2 on 2025-07-16 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audir', '0004_alter_result_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='file',
        ),
    ]
