# Generated by Django 5.2 on 2025-07-16 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audir', '0005_rename_image_image_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='file',
            new_name='image',
        ),
    ]
