# Generated by Django 5.2 on 2025-07-16 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audir', '0008_project_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='slug',
        ),
    ]
